// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoByCity.ListAPI.Model.Context;

#nullable disable

namespace ToDoByCity.ListAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToDoByCity.ListAPI.Model.ToDo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_At");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Currency");

                    b.Property<DateTime>("Deleted_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Deleted_At");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<bool>("Done")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Done");

                    b.Property<DateTime>("Done_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Done_At");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Image");

                    b.Property<string>("Image_Thumb_Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Image_Thumb_Url");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Image_Url");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Language");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Longitude");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Updated_At");

                    b.HasKey("Id");

                    b.ToTable("ToDo");
                });
#pragma warning restore 612, 618
        }
    }
}
